### ISSUE TITLE
 Failed to verify proposal error

### ISSUE THREAD

**Issue by EdsonAlcala** [jpmorganchase/quorum-examples#158] opened 2019-01-28 12:35 UTC
I'm having issues running a quorum setup with 4 nodes that I did following the 7nodes example with Istanbul + Tessera 0.8.

I'm running Quorum v2.2.1
and the information of my from the geth console is:
Geth/Node 1/v1.8.12-stable/linux-amd64/go1.9.4"

For instance I can get a transaction hash but I cannot get the transaction receipt.

0x4e65abb06f66c0710a58d4eaa70b22b953a59e2acd475c2344e86cd7ddd49c4d

eth.getTransactionReceipt("0x4e65abb06f66c0710a58d4eaa70b22b953a59e2acd475c2344e86cd7ddd49c4d")
null

And the logs says

WARN [01-28|12:31:38.979|consensus/istanbul/core/preprepare.go:85]      Failed to verify proposal                address=0x8304cB99e989EE34af465Db1CF15E369D8402870 from=0x8304cB99e989EE34af465Db1CF15E369D8402870 state="Accept request" err="block in the future"                                    duration=20.260243ms

Am I missing something? The same error appears in 7nodes example but with 

"ERROR[01-28|12:40:02.056] Impossible reorg, please file an issue   oldnum=2336 oldhash=67e897…9f12c9 newnum=2336 newhash=67e897…9f12c9"

**Comment by SatpalSandhu61** [comment] 2019-01-28 14:20
Closing this ticket as it's a dupe of https://github.com/jpmorganchase/quorum/issues/631

**Closed as completed by SatpalSandhu61** 2019-01-28 14:20 UTC
