### ISSUE TITLE
Raft no mining blocks, geth is running, but like stupid, repeat following log.......

### ISSUE THREAD

**Issue by ScottGold** [jpmorganchase/quorum-examples#245] opened 2020-10-25 03:55 UTC
TRACE[10-25|03:56:01.719] Node Permissioning is Disabled.          id=cd443935a18c4669 addr=172.31.45.1:9304   conn=staticdial
TRACE[10-25|03:56:01.720] Rejected peer before protocol handshake  id=cd443935a18c4669 addr=172.31.45.1:9304   conn=staticdial err="connected to self"
TRACE[10-25|03:56:01.721] Setting up connection failed             id=cd443935a18c4669 err="connected to self"
TRACE[10-25|03:56:01.721] Dial error                               task="staticdial cd443935a18c4669 172.31.45.1:9304"   err="connected to self"
TRACE[10-25|03:56:01.721] Dial task done                           task="staticdial cd443935a18c4669 172.31.45.1:9304"
TRACE[10-25|03:56:01.721] New dial task                            task="wait for dial hist expire (29.999996095s)"
DEBUG[10-25|03:56:11.655] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s

**Comment by SatpalSandhu61** [comment] 2020-10-26 09:38
Closing this as I believe it's a duplicate of https://github.com/ConsenSys/quorum/issues/1089.
Please re-open if that isn't the case, adding the following information:

- Geth version: geth version
- OS & Version: Windows/Linux/OSX
- Branch, Commit Hash or Release: git status
- geth logs
- genesis.json and static-nodes.json

**Closed as completed by SatpalSandhu61** 2020-10-26 09:38 UTC
